### Part 2

It consists to compute and check similarties of the examples proposed in chapter 2 relative to
collaborative filtering

In [1]:
from IPython.display import display, HTML; display(HTML("<style>.container {width:100% ! important;}</style>"))

In [2]:
%matplotlib inline

In [3]:
import numpy as np 
import pandas as pd

In [4]:
from sklearn.metrics.pairwise import cosine_similarity #For one argument works by row pairs

### Example 1

In [7]:
df1 = pd.read_excel('C://Users//37718890//Downloads/EX1.xlsx')

In [8]:
df1

Name  Item1  Item2  Item3  Item4  Item5  Item6  Item7  Item8
0   U1    NaN    4.0    4.0    2.0      1      2    NaN    NaN
1   U2    3.0    NaN    NaN    NaN      5      1    NaN    NaN

In [22]:
df1 = pd.read_excel('C://Users//37718890//Downloads/EX1.xlsx', index_col='Name')

df1

Item1  Item2  Item3  Item4  Item5  Item6  Item7  Item8
Name                                                        
U1      NaN    4.0    4.0    2.0      1      2    NaN    NaN
U2      3.0    NaN    NaN    NaN      5      1    NaN    NaN

In [23]:
df1 = pd.read_excel('C://Users//37718890//Downloads/EX1.xlsx', index_col='Name').astype(float)

In [24]:
df1

Item1  Item2  Item3  Item4  Item5  Item6  Item7  Item8
Name                                                        
U1      NaN    4.0    4.0    2.0    1.0    2.0    NaN    NaN
U2      3.0    NaN    NaN    NaN    5.0    1.0    NaN    NaN

In [25]:
test1 = df1.fillna(0)

In [26]:
c1 = cosine_similarity(test1)

In [27]:
c1

array([[1.        , 0.18478729],
       [0.18478729, 1.        ]])

In [28]:
pd.DataFrame(c1, index=df1.index, columns=df1.index)

Name        U1        U2
Name                    
U1    1.000000  0.184787
U2    0.184787  1.000000

In [29]:
c11 = cosine_similarity(test1.T)

In [30]:
c11

array([[1.        , 0.        , 0.        , 0.        , 0.98058068,
        0.4472136 , 0.        , 0.        ],
       [0.        , 1.        , 1.        , 1.        , 0.19611614,
        0.89442719, 0.        , 0.        ],
       [0.        , 1.        , 1.        , 1.        , 0.19611614,
        0.89442719, 0.        , 0.        ],
       [0.        , 1.        , 1.        , 1.        , 0.19611614,
        0.89442719, 0.        , 0.        ],
       [0.98058068, 0.19611614, 0.19611614, 0.19611614, 1.        ,
        0.61394061, 0.        , 0.        ],
       [0.4472136 , 0.89442719, 0.89442719, 0.89442719, 0.61394061,
        1.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        ]])

In [31]:
pd.DataFrame(c11, index=df1.T.index, columns=df1.T.index)

Item1     Item2     Item3     Item4     Item5     Item6  Item7  \
Item1  1.000000  0.000000  0.000000  0.000000  0.980581  0.447214    0.0   
Item2  0.000000  1.000000  1.000000  1.000000  0.196116  0.894427    0.0   
Item3  0.000000  1.000000  1.000000  1.000000  0.196116  0.894427    0.0   
Item4  0.000000  1.000000  1.000000  1.000000  0.196116  0.894427    0.0   
Item5  0.980581  0.196116  0.196116  0.196116  1.000000  0.613941    0.0   
Item6  0.447214  0.894427  0.894427  0.894427  0.613941  1.000000    0.0   
Item7  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000    0.0   
Item8  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000    0.0   

       Item8  
Item1    0.0  
Item2    0.0  
Item3    0.0  
Item4    0.0  
Item5    0.0  
Item6    0.0  
Item7    0.0  
Item8    0.0

### Example 2

In [33]:
df2 = pd.read_excel('C://Users//37718890//Downloads/EX2.xlsx')

df2

Name  HP1  HP2  HP3   TW  SW1  SW2  SW3
0    A  4.0  NaN  NaN  5.0  1.0  NaN  NaN
1    B  5.0  5.0  4.0  NaN  NaN  NaN  NaN
2    C  NaN  NaN  NaN  2.0  4.0  5.0  NaN
3    D  NaN  3.0  NaN  NaN  NaN  NaN  3.0

In [34]:
df2 = pd.read_excel('C://Users//37718890//Downloads/EX2.xlsx', index_col='Name')


In [35]:
df2

HP1  HP2  HP3   TW  SW1  SW2  SW3
Name                                   
A     4.0  NaN  NaN  5.0  1.0  NaN  NaN
B     5.0  5.0  4.0  NaN  NaN  NaN  NaN
C     NaN  NaN  NaN  2.0  4.0  5.0  NaN
D     NaN  3.0  NaN  NaN  NaN  NaN  3.0

#### Standard Cosine

In [36]:
test2 = df2.fillna(0)

In [37]:
c2 = cosine_similarity(test2)

In [38]:
pd.DataFrame(c2, index=df2.index, columns=df2.index)

Name         A         B         C         D
Name                                        
A     1.000000  0.379869  0.322031  0.000000
B     0.379869  1.000000  0.000000  0.435194
C     0.322031  0.000000  1.000000  0.000000
D     0.000000  0.435194  0.000000  1.000000

In [39]:
c22 = cosine_similarity(test2.T)

In [40]:
c22

array([[1.        , 0.66958948, 0.78086881, 0.58001479, 0.1515108 ,
        0.        , 0.        ],
       [0.66958948, 1.        , 0.85749293, 0.        , 0.        ,
        0.        , 0.51449576],
       [0.78086881, 0.85749293, 1.        , 0.        , 0.        ,
        0.        , 0.        ],
       [0.58001479, 0.        , 0.        , 1.        , 0.58549055,
        0.37139068, 0.        ],
       [0.1515108 , 0.        , 0.        , 0.58549055, 1.        ,
        0.9701425 , 0.        ],
       [0.        , 0.        , 0.        , 0.37139068, 0.9701425 ,
        1.        , 0.        ],
       [0.        , 0.51449576, 0.        , 0.        , 0.        ,
        0.        , 1.        ]])

In [41]:
pd.DataFrame(c22, index=df2.T.index, columns=df2.T.index)

HP1       HP2       HP3        TW       SW1       SW2       SW3
HP1  1.000000  0.669589  0.780869  0.580015  0.151511  0.000000  0.000000
HP2  0.669589  1.000000  0.857493  0.000000  0.000000  0.000000  0.514496
HP3  0.780869  0.857493  1.000000  0.000000  0.000000  0.000000  0.000000
TW   0.580015  0.000000  0.000000  1.000000  0.585491  0.371391  0.000000
SW1  0.151511  0.000000  0.000000  0.585491  1.000000  0.970143  0.000000
SW2  0.000000  0.000000  0.000000  0.371391  0.970143  1.000000  0.000000
SW3  0.000000  0.514496  0.000000  0.000000  0.000000  0.000000  1.000000

### Centered Cosine

In [42]:
df2.mean(axis=1)

Name
A    3.333333
B    4.666667
C    3.666667
D    3.000000
dtype: float64

In [43]:
df22 = df2.sub(df2.mean(axis=1), axis=0)

In [45]:
test22 = df22.fillna(0)

In [47]:
c222 = cosine_similarity(test22)

c222

array([[ 1.        ,  0.09245003, -0.55908525,  0.        ],
       [ 0.09245003,  1.        ,  0.        ,  0.        ],
       [-0.55908525,  0.        ,  1.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ]])

In [49]:
pd.DataFrame(c222, index=df22.index, columns=df22.index)

Name         A        B         C    D
Name                                  
A     1.000000  0.09245 -0.559085  0.0
B     0.092450  1.00000  0.000000  0.0
C    -0.559085  0.00000  1.000000  0.0
D     0.000000  0.00000  0.000000  0.0